L_s: 1
batch_size: 64
buffer_size: 5000
collect_metrics_period: 500
dynamic: false
gamma: 0.9
learning_rate: 0.001
measure_intergroup_alignment: false
measure_mnemonic: false
migrate_rate: 0.01
models: []
n_agents: 10
n_neighbors: 1
n_subgroups: 1
n_trials: 10
num_layers: 2
num_neurons: 64
p_s: 1
phase_idx: 0
phase_periods:
- 10
- 10
phases:
- no-sharing
- fully-connected
policy: MlpPolicy
project_path: projects/paper/main/task_single_path/shape_no-sharing
recipe_path: lib/wordcraft/recipe_books/single_path.json
rollout_times: []
seed: 0
shape: no-sharing
sharing: true
step_times: []
timer_dynamic_boyd: 0
times: []
total_episodes: 50000
visit: false
visit_duration: 10
